<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NUL1SU7" failures="2" tests="9" name="Default test" time="232.078" errors="0" timestamp="2022-12-05T18:50:38 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="26.903"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="24.445"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.792">
    <failure type="java.lang.AssertionError" message="expected [] but found [Added customer successfully]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Added customer successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.pages.AddCustomer_Page.VerifyExpectedMessage(AddCustomer_Page.java:70)
at stepdefinitions.AddCustomer_Steps.verify_Customer_Craetion(AddCustomer_Steps.java:50)
at ✽.Verify the Customer Created or Not "Added customer successfully" "Created"(file:///C:/Users/Vassar/eclipse-workspace/StanleyC2C-Web/src/test/resources/PositiveFlowFeatures/AddCustomer.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="24.895"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="27.038"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="27.729"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="25.13"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="31.524"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.146">
    <failure type="java.lang.AssertionError" message="expected [] but found [Added customer successfully]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Added customer successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.pages.AddCustomer_Page.VerifyExpectedMessage(AddCustomer_Page.java:70)
at stepdefinitions.AddCustomer_Steps.verify_Customer_Craetion(AddCustomer_Steps.java:50)
at ✽.Verify the Customer Created or Not "Added customer successfully" "Created"(file:///C:/Users/Vassar/eclipse-workspace/StanleyC2C-Web/src/test/resources/PositiveFlowFeatures/AddCustomer.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
